# GitGuardian configuration
version: 2

# Exclude test files and fixtures from secret scanning
paths-ignore:
  - "**/tests/**"
  - "**/*test*.py"
  - "**/conftest.py"
  - "**/.env.example"
  - "**/.env.test"
  - "**/fixtures/**"
  - "**/test_*.py"
  - "**/*_test.py"

# Ignore test token patterns and fake secrets
matches-ignore:
  - name: "Test service tokens"
    match: "test-.*-service-token"
  - name: "Test API keys"
    match: "test-api-key"
  - name: "Test tokens"
    match: "test-.*-token"
  - name: "Fake test tokens"
    match: "fake-test-token"
  - name: "xoxb test tokens"
    match: "xoxb-test"
  - name: "xapp test tokens"
    match: "xapp-test"

# Ignore specific secret types in test files
secret_types:
  - name: "Generic High Entropy Secret"
    path_exceptions:
      - "**/tests/**"
      - "**/conftest.py"
  - name: "Generic Password"
    path_exceptions:
      - "**/tests/**"
      - "**/conftest.py"
