#!/bin/sh
set -e

# Use mounted SSL certificates from host (generated by scripts/setup-ssl.sh)
# Certificates are mounted at /app/ssl/ from host's .ssl/ directory

# Generate langgraph.json dynamically based on available agents
echo "Generating langgraph.json..."
python3 /app/generate_langgraph_config.py

# Start Gunicorn with HTTPS
# Note: --forwarded-allow-ips='*' allows proxy headers from any source (safe in internal Docker network)
exec gunicorn \
    --bind 0.0.0.0:8000 \
    --workers 4 \
    --worker-class uvicorn.workers.UvicornWorker \
    --timeout 120 \
    --forwarded-allow-ips '*' \
    --access-logfile - \
    --error-logfile - \
    --keyfile /app/ssl/agent-service-key.pem \
    --certfile /app/ssl/agent-service-cert.pem \
    app:app
