"""Create scheduled_tasks and task_runs tables

Revision ID: 001
Revises:
Create Date: 2025-09-24 02:45:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scheduled_tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(length=255), nullable=False),
        sa.Column("job_type", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("schedule_config", sa.JSON(), nullable=False),
        sa.Column("params", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="1"),
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scheduled_tasks")),
    )
    op.create_index(
        op.f("ix_scheduled_tasks_job_id"),
        "scheduled_tasks",
        ["job_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_scheduled_tasks_job_type"),
        "scheduled_tasks",
        ["job_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_tasks_is_active"),
        "scheduled_tasks",
        ["is_active"],
        unique=False,
    )

    op.create_table(
        "task_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column(
            "triggered_by",
            sa.String(length=100),
            nullable=True,
            server_default="scheduler",
        ),
        sa.Column("triggered_by_user", sa.String(length=255), nullable=True),
        sa.Column("task_config_snapshot", sa.JSON(), nullable=True),
        sa.Column("result_data", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_traceback", sa.Text(), nullable=True),
        sa.Column("log_output", sa.Text(), nullable=True),
        sa.Column("records_processed", sa.Integer(), nullable=True),
        sa.Column("records_success", sa.Integer(), nullable=True),
        sa.Column("records_failed", sa.Integer(), nullable=True),
        sa.Column("environment_info", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_runs")),
    )
    op.create_index(
        op.f("ix_task_runs_run_id"),
        "task_runs",
        ["run_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_task_runs_status"),
        "task_runs",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_runs_started_at"),
        "task_runs",
        ["started_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_runs_started_at"), table_name="task_runs")
    op.drop_index(op.f("ix_task_runs_status"), table_name="task_runs")
    op.drop_index(op.f("ix_task_runs_run_id"), table_name="task_runs")
    op.drop_table("task_runs")

    op.drop_index(op.f("ix_scheduled_tasks_is_active"), table_name="scheduled_tasks")
    op.drop_index(op.f("ix_scheduled_tasks_job_type"), table_name="scheduled_tasks")
    op.drop_index(op.f("ix_scheduled_tasks_job_id"), table_name="scheduled_tasks")
    op.drop_table("scheduled_tasks")
    # ### end Alembic commands ###
