"""Add task_runs table for execution history

Revision ID: 7fd63376f213
Revises: dfb18e519ba6
Create Date: 2025-09-23 16:06:22.419104

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7fd63376f213"
down_revision = "dfb18e519ba6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scheduled_task_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("triggered_by", sa.String(length=100), nullable=True),
        sa.Column("triggered_by_user", sa.String(length=255), nullable=True),
        sa.Column("result_data", sa.JSON(), nullable=True),
        sa.Column("log_output", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_traceback", sa.Text(), nullable=True),
        sa.Column("records_processed", sa.Integer(), nullable=True),
        sa.Column("records_success", sa.Integer(), nullable=True),
        sa.Column("records_failed", sa.Integer(), nullable=True),
        sa.Column("task_config_snapshot", sa.JSON(), nullable=True),
        sa.Column("environment_info", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scheduled_task_id"],
            ["scheduled_tasks.id"],
            name=op.f("fk_task_runs_scheduled_task_id_scheduled_tasks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_runs")),
    )
    op.create_index(op.f("ix_task_runs_run_id"), "task_runs", ["run_id"], unique=True)
    op.create_index(
        op.f("ix_task_runs_scheduled_task_id"),
        "task_runs",
        ["scheduled_task_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_runs_scheduled_task_id"), table_name="task_runs")
    op.drop_index(op.f("ix_task_runs_run_id"), table_name="task_runs")
    op.drop_table("task_runs")
    # ### end Alembic commands ###
