"""remove scheduled_task_id from task_runs table

Revision ID: fd9c3becd798
Revises: 7fd63376f213
Create Date: 2025-09-23 20:07:24.132114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd9c3becd798'
down_revision = '7fd63376f213'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only remove the scheduled_task_id from task_runs table
    try:
        op.drop_constraint(op.f('fk_task_runs_scheduled_task_id_scheduled_tasks'), 'task_runs', type_='foreignkey')
    except:
        pass  # Constraint might not exist

    try:
        op.drop_index(op.f('ix_task_runs_scheduled_task_id'), table_name='task_runs')
    except:
        pass  # Index might not exist

    try:
        op.drop_column('task_runs', 'scheduled_task_id')
    except:
        pass  # Column might not exist
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_runs', sa.Column('scheduled_task_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_task_runs_scheduled_task_id_scheduled_tasks'), 'task_runs', 'scheduled_tasks', ['scheduled_task_id'], ['id'])
    op.create_index(op.f('ix_task_runs_scheduled_task_id'), 'task_runs', ['scheduled_task_id'], unique=False)
    op.create_table('apscheduler_jobs',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('next_run_time', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.create_table('scheduled_tasks',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('task_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('schedule_expression', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('task_config', mysql.JSON(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('last_run_at', mysql.DATETIME(), nullable=True),
    sa.Column('next_run_at', mysql.DATETIME(), nullable=True),
    sa.Column('last_status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('last_error', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('total_runs', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('successful_runs', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('failed_runs', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_scheduled_tasks_task_id'), 'scheduled_tasks', ['task_id'], unique=True)
    # ### end Alembic commands ###
