#!/bin/sh
set -e

# Use mounted SSL certificates from host (generated by scripts/setup-ssl.sh)
# Certificates are mounted at /app/ssl/ from host's .ssl/ directory

# Start the FastAPI app with Uvicorn
exec uvicorn app:app --host 0.0.0.0 --port 6001 --workers 4 \
    --ssl-keyfile /app/ssl/control-plane-key.pem \
    --ssl-certfile /app/ssl/control-plane-cert.pem
