"""Create slack_users table with user_type field

Revision ID: 001
Revises:
Create Date: 2025-09-24 02:45:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "slack_users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("slack_user_id", sa.String(length=255), nullable=False),
        sa.Column("email_address", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("real_name", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="1"),
        sa.Column("user_type", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_slack_users")),
    )
    op.create_index(
        op.f("ix_slack_users_email_address"),
        "slack_users",
        ["email_address"],
        unique=False,
    )
    op.create_index(
        op.f("ix_slack_users_slack_user_id"),
        "slack_users",
        ["slack_user_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_slack_users_is_active"),
        "slack_users",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_slack_users_user_type"),
        "slack_users",
        ["user_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_slack_users_user_type"), table_name="slack_users")
    op.drop_index(op.f("ix_slack_users_is_active"), table_name="slack_users")
    op.drop_index(op.f("ix_slack_users_slack_user_id"), table_name="slack_users")
    op.drop_index(op.f("ix_slack_users_email_address"), table_name="slack_users")
    op.drop_table("slack_users")
    # ### end Alembic commands ###
