"""Create slack_usage table for tracking interactions

Revision ID: 007
Revises: 006
Create Date: 2025-01-29 12:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "007"
down_revision = "006"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "slack_usage",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("slack_user_id", sa.String(length=255), nullable=False),
        sa.Column("thread_ts", sa.String(length=255), nullable=False),
        sa.Column("channel_id", sa.String(length=255), nullable=True),
        sa.Column(
            "interaction_type",
            sa.String(length=50),
            nullable=False,
            server_default="message",
        ),
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_slack_usage")),
    )
    op.create_index(
        op.f("ix_slack_usage_slack_user_id"),
        "slack_usage",
        ["slack_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_slack_usage_thread_ts"),
        "slack_usage",
        ["thread_ts"],
        unique=False,
    )
    op.create_index(
        op.f("ix_slack_usage_channel_id"),
        "slack_usage",
        ["channel_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_slack_usage_created_at"),
        "slack_usage",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_slack_usage_created_at"), table_name="slack_usage")
    op.drop_index(op.f("ix_slack_usage_channel_id"), table_name="slack_usage")
    op.drop_index(op.f("ix_slack_usage_thread_ts"), table_name="slack_usage")
    op.drop_index(op.f("ix_slack_usage_slack_user_id"), table_name="slack_usage")
    op.drop_table("slack_usage")
    # ### end Alembic commands ###
