"""Create librechat_usage table for tracking UI interactions

Revision ID: 008
Revises: 007
Create Date: 2025-01-29 13:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "008"
down_revision = "007"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "librechat_usage",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("conversation_id", sa.String(length=255), nullable=False),
        sa.Column("agent_used", sa.String(length=100), nullable=True),
        sa.Column("deep_search", sa.String(length=10), nullable=True),
        sa.Column(
            "interaction_type",
            sa.String(length=50),
            nullable=False,
            server_default="message",
        ),
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_librechat_usage")),
    )
    op.create_index(
        op.f("ix_librechat_usage_user_id"),
        "librechat_usage",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_librechat_usage_email"),
        "librechat_usage",
        ["email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_librechat_usage_conversation_id"),
        "librechat_usage",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_librechat_usage_created_at"),
        "librechat_usage",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_librechat_usage_created_at"), table_name="librechat_usage")
    op.drop_index(
        op.f("ix_librechat_usage_conversation_id"), table_name="librechat_usage"
    )
    op.drop_index(op.f("ix_librechat_usage_email"), table_name="librechat_usage")
    op.drop_index(op.f("ix_librechat_usage_user_id"), table_name="librechat_usage")
    op.drop_table("librechat_usage")
    # ### end Alembic commands ###
